---
executors:
  unity:
    working_directory: /tmp/workspace
    docker:
      - image: "${AWS_ID}.dkr.ecr.us-east-2.amazonaws.com/circleci-build-unity:2020.3.33f1"
        aws_auth:
           aws_access_key_id: $CIRCLECI_AWS_ACCESS_KEY_ID
           aws_secret_access_key: $CIRCLECI_AWS_SECRET_ACCESS_KEY
  npm:
    working_directory: /tmp/workspace
    docker:
      - image: "${AWS_ID}.dkr.ecr.us-east-2.amazonaws.com/circleci-build-ubuntu-18-node-10:latest"
        aws_auth:
           aws_access_key_id: $CIRCLECI_AWS_ACCESS_KEY_ID
           aws_secret_access_key: $CIRCLECI_AWS_SECRET_ACCESS_KEY

version: 2.1
jobs:
  run_tests:
    executor: unity
    steps:
      - run: 
          name: 'Find clone name'
          command: |
             if [[ "$CIRCLE_BRANCH" == "" ]]; then
                echo 'export CLONED=$CIRCLE_TAG' >> $BASH_ENV
             else
                echo 'export CLONED=$CIRCLE_BRANCH' >> $BASH_ENV
              fi
              echo "Cloning ${CLONED} branch/tag."
      - run: git clone https://${GITHUB_TOKEN}@github.com/homagames/hg-mobile-unitypackage-ci-environment.git .
      - run: git clone --depth 5 https://${GITHUB_TOKEN}@github.com/homagames/${CIRCLE_PROJECT_REPONAME}.git --branch "$CLONED" "Packages/$CIRCLE_PROJECT_REPONAME"
      - run:
          name: 'Run Tests'
          command: |
            bash Packages/${CIRCLE_PROJECT_REPONAME}/.circleci/run_tests.sh
  artifactory:
    executor: npm
    steps:
      - checkout
      - run:
          name: 'Upload Unity packages to artifactory'
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" \
                    'https://raw.githubusercontent.com/homagames/hg-cicd-common/master/mobile/unitypackages/unitypackage_to_artifactory.sh' | bash
  homabelly:
    executor: unity
    steps:
      - run: git clone https://${GITHUB_TOKEN}@github.com/homagames/hg-mobile-unitypackage-ci-environment.git .
      - run: git clone --depth 5 https://${GITHUB_TOKEN}@github.com/homagames/${CIRCLE_PROJECT_REPONAME}.git --branch "$CIRCLE_TAG" "Packages/$CIRCLE_PROJECT_REPONAME"
      - run: 
          name: "Activate Unity License"
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" "https://raw.githubusercontent.com/homagames/hg-cicd-common/master/mobile/licenses/activate_unity_license.sh" | bash
      - run:
          name: "Build Homa Belly Packages"
          command: |
            echo "Building Packages..."
            unity-editor -batchmode -nographics -quit -projectpath . -executeMethod Build.CreateAllEmbeddedUnityPackages -buildTarget Android
      - run: 
          name: "Return Unity License"
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" "https://raw.githubusercontent.com/homagames/hg-cicd-common/master/mobile/licenses/return_unity_license.sh" | bash
      - run:
          name: "Upload Game Doctor to S3"
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" "https://raw.githubusercontent.com/homagames/hg-cicd-common/master/mobile/homa_belly/upload_packages.sh" | bash
  merge_into_master:
    executor: unity
    steps:
      - attach_workspace: {at: /tmp/workspace}
      - run:
          name: "Merging develop into master"
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" "https://raw.githubusercontent.com/homagames/hg-cicd-common/master/mobile/homa_belly/merge_into_master.sh" | bash

orbs:
  slack: circleci/slack@1.0.0

workflows:
  version: 2
  build-to-release:
    jobs:
      - run_tests:
          context:
          - hg-common
          - hg-mobile
          - hg-unity
          - hg-damysus
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - develop
      - artifactory:
          context:
          - hg-common
          - hg-mobile
          - hg-unity
          requires:
            - run_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - homabelly:
          context:
          - hg-common
          - hg-mobile
          - hg-damysus
          - hg-unity
          requires:
            - run_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - merge_into_master:
          context:
          - hg-common
          - hg-mobile
          - hg-unity
          requires:
            - artifactory
            - homabelly
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/