name: Release package

on:
  release:
    types: [published]

jobs:
  tests:
    uses: homagames/unity-ci-environment/.github/workflows/run-tests.yml@master
    secrets: inherit
  build-package:
    uses: homagames/unity-ci-environment/.github/workflows/build-package.yml@master
    secrets: inherit
    needs: tests
  github-release:
    uses: homagames/unity-ci-environment/.github/workflows/github-release.yml@master
    secrets: inherit
    needs: build-package
  upm-release:
    uses: homagames/unity-ci-environment/.github/workflows/upm-release.yml@master
    secrets: inherit
    needs: build-package
